# YAML file contains Shared defaults values that work for most people or envs

project_name: Tracking Config
# This one called Literal block, there is another one called Folded (>)
project_desc: |
  Tracking System for detection, providing real-time camera status throught a Dashboard.
task: indoor
intervals:
  system_metrics_seconds: 3.0 # Logging system metrics every
  frames_summary_every: 30 # Number of frames to create a logs summary
  realtime_updates_every: 2 # backend send updates every n seconds?

yolo:
  model_name: "yolo26n.pt"
  classes:
    - person
  batch_size: 16
  epochs: 100
  wandb: True
  augment: True
  data_path: ""

security_detector:
  model_name: "yolo_smoke_fire.pt"
  classes:
    - fire
    - smoke

depth:
  model_name: "depth_anything_v2_vits.pth"
  device: "cpu"
  encoder: "vits"
