repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.4
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: local # It is on the local machine
    hooks:
      - id: pytest
        name: Run Unit Tests
        entry: pytest backend/tests/ # CMD to run
        language: system # Use local python
        pass_filenames: false # Run all, not only the modified one
        always_run: true
